-- 기사 댓글 테이블 생성
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL, -- articles 테이블의 id를 참조 (일단 news와 통합 관리 중이므로 단순 BIGINT)
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- 작성자 고유 ID
    user_name TEXT, -- 작성자 닉네임/이름 (스냅샷용)
    content TEXT NOT NULL, -- 댓글 내용
    likes INTEGER DEFAULT 0, -- 추천 수
    dislikes INTEGER DEFAULT 0, -- 비추천 수
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_comments_article_id ON public.comments(article_id);

-- 권한 설정 (RLS)
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- 누구나 댓글을 읽을 수 있음
CREATE POLICY "Public profiles are viewable by everyone."
ON public.comments FOR SELECT
USING ( true );

-- 로그인된 사용자만 댓글을 작성할 수 있음
CREATE POLICY "Users can insert their own comments."
ON public.comments FOR INSERT
WITH CHECK ( auth.uid() = user_id );

-- 본인의 댓글만 수정/삭제할 수 있음
CREATE POLICY "Users can update own comments."
ON public.comments FOR UPDATE
USING ( auth.uid() = user_id );

CREATE POLICY "Users can delete own comments."
ON public.comments FOR DELETE
USING ( auth.uid() = user_id );
