-- [공실뉴스 지도 서비스를 위한 테이블 생성 SQL]
-- Supabase 대시보드 -> SQL Editor -> New Query 에 붙여넣고 Run 해주세요.

-- 1. news 테이블 생성
create table if not exists public.news (
    id bigint generated by default as identity primary key,
    title text not null,
    link text not null unique,
    description text,
    author text,
    pub_date timestamptz,
    image_url text,
    lat float8,
    lng float8,
    source text default 'gongsilnews',
    created_at timestamptz default now()
);

-- 2. 검색 및 지도 조회를 위한 인덱스 생성
create index if not exists news_link_idx on public.news (link);
create index if not exists news_geo_idx on public.news (lat, lng);
create index if not exists news_pub_date_idx on public.news (pub_date desc);

-- 3. 권한 설정 (중요: 공개 키로 저장할 수 있도록 허용)
alter table public.news enable row level security;

-- 기존 정책 제거 (재실행 시 에러 방지)
drop policy if exists "Allow all access" on public.news;

-- 모든 사용자에게 읽기/쓰기 허용 정책 추가
create policy "Allow all access"
on public.news
for all
using (true)
with check (true);

-- 4. members 테이블 생성 및 관리 (회원 구분 및 등급 관리)
create table if not exists public.members (
    id uuid primary key,
    email text not null unique,
    role text default 'general',
    membership text default 'free',
    member_num bigint generated always as identity,
    membership_start_at timestamptz,
    expired_at timestamptz,
    created_at timestamptz default now()
);

-- 인덱스 및 RLS 설정
create index if not exists members_email_idx on public.members (email);
alter table public.members enable row level security;

drop policy if exists "Allow all access" on public.members;
create policy "Allow all access"
on public.members
for all
using (true)
with check (true);

-- 5. properties 테이블 생성 (매물 등록 정보)
CREATE TABLE IF NOT EXISTS public.properties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id),
    user_role text DEFAULT 'general', -- 등록 당시 권한 (general / realtor)
    
    -- 매물 기본 정보
    property_type text NOT NULL,      -- 아파트, 상가 등
    trade_type text NOT NULL,         -- 매매, 전세, 월세, 단기
    deposit bigint DEFAULT 0,         -- 보증금 / 매매가
    monthly_rent bigint DEFAULT 0,    -- 월세
    maintenance_fee bigint DEFAULT 0, -- 관리비
    
    -- 상세 사양
    room_count text,
    bathroom_count text,
    supply_area float8,               -- 공급면적 (m2)
    area float8,                      -- 전용면적 (m2)
    options text,                     -- 옵션 (콤마 구분)
    
    -- 주소 정보
    sido text,
    sigungu text,
    dong text,
    detail_address text,
    building_name text,
    dong_number text,
    room_number text,
    is_room_private boolean DEFAULT false,
    
    -- 비고 및 의뢰인 정보
    description text,                 -- 상세 설명
    author_name text,                 -- 의뢰인/작성자 성함
    author_phone text,                -- 의뢰인/작성자 연락처
    owner_relation text,              -- 소유주와의 관계 (또는 중개사 전용 메모)
    brokerage_fee text,               -- 중개보수 지급 여부/비율
    
    -- 이미지 및 상태
    images text[],                    -- 이미지 URL 배열 (최대 5장)
    agree_promo boolean DEFAULT false, -- 광고 동의 여부
    status text DEFAULT 'active',     -- 상태 (pending, active, sold, hidden)
    
    -- 통계 및 시간
    view_count int DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 인덱스 추가 (조회 성능 향상)
CREATE INDEX IF NOT EXISTS properties_user_id_idx ON public.properties (user_id);
CREATE INDEX IF NOT EXISTS properties_status_idx ON public.properties (status);
CREATE INDEX IF NOT EXISTS properties_geo_idx ON public.properties (dong);

-- RLS 설정
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view active properties" ON public.properties;
CREATE POLICY "Anyone can view active properties"
ON public.properties FOR SELECT
USING (true); -- 지도 및 리스트 노출을 위해 전체 공개 (상세 정보는 앱 로직에서 제어)

DROP POLICY IF EXISTS "Users can insert their own properties" ON public.properties;
CREATE POLICY "Users can insert their own properties"
ON public.properties FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own properties" ON public.properties;
CREATE POLICY "Users can update their own properties"
ON public.properties FOR UPDATE
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own properties" ON public.properties;
CREATE POLICY "Users can delete their own properties"
ON public.properties FOR DELETE
USING (auth.uid() = user_id);
