-- [공실뉴스 지도 서비스를 위한 테이블 생성 SQL]
-- Supabase 대시보드 -> SQL Editor -> New Query 에 붙여넣고 Run 해주세요.

-- 1. news 테이블 생성
create table if not exists public.news (
    id bigint generated by default as identity primary key,
    title text not null,
    link text not null unique,
    description text,
    author text,
    pub_date timestamptz,
    image_url text,
    lat float8,
    lng float8,
    source text default 'gongsilnews',
    created_at timestamptz default now()
);

-- 2. 검색 및 지도 조회를 위한 인덱스 생성
create index if not exists news_link_idx on public.news (link);
create index if not exists news_geo_idx on public.news (lat, lng);
create index if not exists news_pub_date_idx on public.news (pub_date desc);

-- 3. 권한 설정 (중요: 공개 키로 저장할 수 있도록 허용)
alter table public.news enable row level security;

-- 기존 정책 제거 (재실행 시 에러 방지)
drop policy if exists "Allow all access" on public.news;

-- 모든 사용자에게 읽기/쓰기 허용 정책 추가
create policy "Allow all access"
on public.news
for all
using (true)
with check (true);

-- 4. members 테이블 생성 및 관리 (회원 구분 및 등급 관리)
create table if not exists public.members (
    id uuid primary key,
    email text not null unique,
    role text default 'general',
    membership text default 'free',
    member_num bigint generated always as identity,
    membership_start_at timestamptz,
    expired_at timestamptz,
    created_at timestamptz default now()
);

-- 인덱스 및 RLS 설정
create index if not exists members_email_idx on public.members (email);
alter table public.members enable row level security;

drop policy if exists "Allow all access" on public.members;
create policy "Allow all access"
on public.members
for all
using (true)
with check (true);

-- 5. properties 테이블 생성 (매물 등록 정보)
create table if not exists public.properties (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id),
    property_type text not null,
    trade_type text not null,
    deposit bigint default 0,
    monthly_rent bigint default 0,
    maintenance_fee bigint default 0,
    room_count text,
    bathroom_count text,
    supply_area float8,
    area float8,
    options text,
    sido text,
    sigungu text,
    dong text,
    detail_address text,
    building_name text,
    dong_number text,
    room_number text,
    is_room_private boolean default false,
    description text,
    author_name text,
    author_phone text,
    owner_relation text,
    brokerage_fee text,
    agree_promo boolean default false,
    status text default 'pending',
    created_at timestamptz default now()
);

-- RLS 설정
alter table public.properties enable row level security;

drop policy if exists "Users can manage their own properties" on public.properties;
create policy "Users can manage their own properties"
on public.properties
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
